import type { Metadata } from "next";
import { Crimson_Text } from "next/font/google";
import "./globals.css";
import { Header } from "../components/Header/Header";
import { ToastRegion } from "@/components/ToastRegion/ToastRegion";

const crimson_text = Crimson_Text({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${crimson_text.className}`}>
        <Header />
        <ToastRegion />
        {children}
      </body>
    </html>
  );
}
