'use server'
export const SUPABASE_URL = process.env.SUPABASE_URL || ''
export const SUPABASE_KEY = process.env.SUPABASE_PUBLIC_KEY || ''
export const HEADER_AUTH = 'x-auth-user-id'
export const HEADER_CURRENT_PATH ='x-current-pathname'